ca/src/ReqTrack/Application.Web.MVC/ViewModels/Requirements/AddRequirementViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReqTrack.Domain.Core.Entities.ValidationHelpers;

namespace ReqTrack.Application.Web.MVC.ViewModels.Requirements
{
    public class AddRequirementViewModel : ViewModel
    {
        public AddRequirementViewModel() : this(null, null) { }

        public AddRequirementViewModel(string userId, string userName) : base(userId, userName)
        {
        }

        [HiddenInput]
        public string ProjectId { get; set; }

        [HiddenInput]
        [DisplayName("Project name")]
        public string ProjectName { get; set; }

        [DisplayName("Title")]
        [StringLength(RequirementValidationHelper.MaximumTitleLength, ErrorMessage = "Title is too long.")]
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Type is required")]
        public string Type { get; set; }

        [DisplayName("Note")]
        [StringLength(RequirementValidationHelper.MaximumNoteLength, ErrorMessage = "Note is too long.")]
        public string Note { get; set; }

        [HiddenInput]
        public SelectListItem[] Types { get; set; } 
    }
}

ca/src/ReqTrack/Application.Web.MVC/ViewModels/Requirements/ChangeRequirementViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReqTrack.Domain.Core.Entities.ValidationHelpers;

namespace ReqTrack.Application.Web.MVC.ViewModels.Requirements
{
    public class ChangeRequirementViewModel : ViewModel
    {
        public ChangeRequirementViewModel() : this(null, null) { }

        public ChangeRequirementViewModel(string userId, string userName) : base(userId, userName)
        {
        }

        [HiddenInput] public string ProjectId { get; set; }

        [HiddenInput] public string RequirementId { get; set; }

        [HiddenInput]
        [DisplayName("Project name")]
        public string ProjectName { get; set; }

        [DisplayName("Title")]
        [StringLength(RequirementValidationHelper.MaximumTitleLength, ErrorMessage = "Title is too long.")]
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Type is required")]
        public string Type { get; set; }

        [DisplayName("Note")]
        [StringLength(RequirementValidationHelper.MaximumNoteLength, ErrorMessage = "Note is too long.")]
        public string Note { get; set; }

        [HiddenInput]
        public SelectListItem[] Types { get; set; }
    }
}

ca/src/ReqTrack/Application.Web.MVC/ViewModels/Requirements/RequirementViewModel.cs
using System.Collections.Generic;

namespace ReqTrack.Application.Web.MVC.ViewModels.Requirements
{
    public class RequirementViewModel
    {
        public string Id { get; set; }

        public string Title { get; set; }

        public string Type { get; set; }

        public string Details { get; set; }

        public string ProjectId { get; set; }

        public IEnumerable<string> RequirementTypes { get; set; }
    }
}

ca/src/ReqTrack/Application.Web.MVC/ViewModels/Requirements/ViewRequirementViewModel.cs
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc;

namespace ReqTrack.Application.Web.MVC.ViewModels.Requirements
{
    public class ViewRequirementViewModel : ViewModel
    {
        public ViewRequirementViewModel(string userId, string userName) : base(userId, userName)
        {
        }

        [HiddenInput]
        public string ProjectId { get; set; }

        [HiddenInput]
        public string RequirementId { get; set; }

        [HiddenInput]
        public string UserId { get; set; }

        [DisplayName("Project name")]
        public string ProjectName { get; set; }

        [DisplayName("Last changed by")]
        public string UserDisplayName { get; set; }

        [DisplayName("Title")]
        public string Title { get; set; }

        [DisplayName("Type")]
        public string Type { get; set; }

        [DisplayName("Note")]
        public string Note { get; set; }

        [HiddenInput]
        public bool CanChange { get; set; }
    }
}

ca/src/ReqTrack/Application.Web.MVC/Controllers/RequirementsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReqTrack.Application.Web.MVC.Factories;
using ReqTrack.Application.Web.MVC.Factories.Default;
using ReqTrack.Application.Web.MVC.ViewModels.Requirements;
using ReqTrack.Domain.Core.UseCases.Factories;
using ReqTrack.Domain.Core.UseCases.Requirements.AddRequirement;
using ReqTrack.Domain.Core.UseCases.Requirements.ChangeRequirement;
using ReqTrack.Domain.Core.UseCases.Requirements.DeleteRequirement;
using ReqTrack.Domain.Core.UseCases.Requirements.ViewRequirement;
using ReqTrack.Runtime.Core.Registry;

namespace ReqTrack.Application.Web.MVC.Controllers
{
    public class RequirementsController : Controller
    {
        private readonly IRequirementUseCaseFactory _requirementUseCaseFactory;

        private readonly IRequirementPresenterFactory _requirementPresenterFactory;

        public RequirementsController()
        {
            _requirementUseCaseFactory = RegistryProxy.Get.GetFactory<IRequirementUseCaseFactory>();
            _requirementPresenterFactory = new RequirementPresenterFactory();
        }

        [HttpGet]
        public IActionResult Index(string projectId, string id)
        {
            var uc = _requirementUseCaseFactory.ViewRequirement;
            var request = new ViewRequirementRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = projectId,
                RequirementId = id,
            };

            var presenter = _requirementPresenterFactory.ViewRequirement(HttpContext.Session, TempData, ModelState);
            if(!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpGet]
        public IActionResult Create(string id)
        {
            var uc = _requirementUseCaseFactory.AddRequirement;
            var request = new AddRequirementInitialRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = id,
            };

            var presenter = _requirementPresenterFactory.AddRequirement(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpPost]
        public IActionResult Create(AddRequirementViewModel vm)
        {
            var uc = _requirementUseCaseFactory.AddRequirement;
            var request = new AddRequirementRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = vm.ProjectId,
                Type = vm.Type,
                Title = vm.Title,
                Note = vm.Note,
            };

            var presenter = _requirementPresenterFactory.AddRequirement(HttpContext.Session, TempData, ModelState);
            if(!uc.Execute(presenter, request)) { return View(vm); }

            return RedirectToAction(nameof(Index), new
            {
                projectId = presenter.Response.ProjectId,
                id = presenter.Response.GivenId
            });
        }

        [HttpGet]
        public IActionResult Change(string projectId, string id)
        {
            var uc = _requirementUseCaseFactory.ChangeRequirement;
            var request = new ChangeRequirementInitialRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = projectId,
                RequirementId = id,
            };

            var presenter = _requirementPresenterFactory.ChangeRequirement(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpPost]
        public IActionResult Change(ChangeRequirementViewModel vm)
        {
            var uc = _requirementUseCaseFactory.ChangeRequirement;
            var request = new ChangeRequirementRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = vm.ProjectId,
                RequirementId = vm.RequirementId,
                Type = vm.Type,
                Title = vm.Title,
                Note = vm.Note,
            };

            var presenter = _requirementPresenterFactory.ChangeRequirement(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            return RedirectToAction(nameof(Index), new
            {
                projectId = presenter.Response.ProjectId,
                id = presenter.Response.RequirementId,
            });
        }

        [HttpGet]
        public IActionResult Delete(string projectId, string id)
        {
            var uc = _requirementUseCaseFactory.DeleteRequirement;
            var request = new DeleteRequirementRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = projectId,
                RequirementId = id,
            };

            var presenter = _requirementPresenterFactory.Default<DeleteRequirementResponse>(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return RedirectToAction(nameof(Index), "Projects",
                new
                {
                    id = projectId,
                    showRequirements = true,
                    showUseCases = false
                }
            );
        }
    }
}

ca/src/ReqTrack/Application.Web.MVC/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReqTrack.Application.Web.MVC.Factories;
using ReqTrack.Application.Web.MVC.Factories.Default;
using ReqTrack.Application.Web.MVC.ViewModels.Users;
using ReqTrack.Domain.Core.UseCases.Factories;
using ReqTrack.Domain.Core.UseCases.Users.AuthorizeUser;
using ReqTrack.Domain.Core.UseCases.Users.ChangeInformation;
using ReqTrack.Domain.Core.UseCases.Users.ChangePassword;
using ReqTrack.Domain.Core.UseCases.Users.DeleteUser;
using ReqTrack.Domain.Core.UseCases.Users.RegisterUser;
using ReqTrack.Domain.Core.UseCases.Users.ViewProfile;
using ReqTrack.Runtime.Core.Registry;

namespace ReqTrack.Application.Web.MVC.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly IUserUseCaseFactory _userUseCaseFactory;

        private readonly IUserPresenterFactory _userPresenterFactory;

        public UsersController()
        {
            _userUseCaseFactory = RegistryProxy.Get.GetFactory<IUserUseCaseFactory>();
            _userPresenterFactory = new UserPresenterFactory();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult LogIn()
        {
            return View(new LogInViewModel());
        }

        [HttpPost]
        [AllowAnonymous]
        [AutoValidateAntiforgeryToken]
        public IActionResult LogIn(LogInViewModel vm)
        {
            var uc = _userUseCaseFactory.AuthorizeUser;
            var request = new AuthorizeUserRequest(null)
            {
                UserName = vm.UserName,
                Password = vm.Password,
            };

            var presenter = _userPresenterFactory.Default<AuthorizeUserResponse>(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            HttpContext.Session.SetString("UserId", presenter.Response.UserId);
            HttpContext.Session.SetString("UserName", presenter.Response.DisplayName);

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, vm.UserName),
            };

            var userIdentity = new ClaimsIdentity(claims, "login");

            var principal = new ClaimsPrincipal(userIdentity);
            HttpContext.SignInAsync(principal).Wait();

            return RedirectToAction(nameof(Index), new {id = presenter.Response.UserId});
        }

        [HttpGet]
        public IActionResult SignOut()
        {
            HttpContext.Session.Clear();

            HttpContext.SignOutAsync().Wait();
            return Redirect("/");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult RegisterUser()
        {
            return View(new RegisterUserViewModel());
        }

        [HttpPost]
        [AllowAnonymous]
        [AutoValidateAntiforgeryToken]
        public IActionResult RegisterUser(RegisterUserViewModel vm)
        {
            var uc = _userUseCaseFactory.RegisterUser;
            var request = new RegisterUserRequest
            {
                UserName = vm.UserName,
                DisplayName = vm.DisplayName,
                Password = vm.Password,
                ConfirmedPassword = vm.ConfirmPassword,
            };

            var presenter = _userPresenterFactory.Default<RegisterUserResponse>(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            return Redirect(nameof(LogIn));
        }

        [HttpGet]
        public IActionResult Index(string id)
        {
            var uc = _userUseCaseFactory.ViewProfile;
            var request = new ViewProfileRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = id,
            };

            var presenter = _userPresenterFactory.ViewProfile(HttpContext.Session, TempData, ModelState);
            if(!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpGet]
        public IActionResult ChangeInformation(string id)
        {
            var uc = _userUseCaseFactory.ChangeInformation;
            var request = new ChangeInformationInitialRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = id,
            };

            var presenter = _userPresenterFactory.ChangeInformation(HttpContext.Session, TempData, ModelState);
            if(!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangeInformation(ChangeInformationViewModel vm)
        {
            var uc = _userUseCaseFactory.ChangeInformation;
            var request = new ChangeInformationRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = vm.ApplicationUserId,
                DisplayName = vm.DisplayName,
            };

            var presenter = _userPresenterFactory.ChangeInformation(HttpContext.Session, TempData, ModelState);
            if(!uc.Execute(presenter, request)) { return View(vm); }

            return RedirectToAction(nameof(Index), new { id = presenter.Response.UserId });
        }

        [HttpGet]
        public IActionResult ChangePassword(string id)
        {
            var uc = _userUseCaseFactory.ChangePassword;
            var request = new ChangePasswordInitialRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = id,
            };

            var presenter = _userPresenterFactory.ChangePassword(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangePassword(ChangePasswordViewModel vm)
        {
            var uc = _userUseCaseFactory.ChangePassword;
            var request = new ChangePasswordRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = vm.ApplicationUserId,
                OldPassword = vm.OldPassword,
                NewPassword = vm.NewPassword,
                ConfirmedPassword = vm.ConfirmedPassword,
            };

            var presenter = _userPresenterFactory.ChangePassword(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            return RedirectToAction(nameof(Index), new { id = presenter.Response.UserId });
        }

        [HttpGet]
        public IActionResult DeleteUser(string id)
        {
            var uc = _userUseCaseFactory.DeleteUser;
            var request = new DeleteUserRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = id,
            };

            var presenter = _userPresenterFactory.Default<DeleteUserResponse>(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return RedirectToAction(nameof(LogIn));
        }
    }
}

ca/src/ReqTrack/Application.Web.MVC/Views/Requirements/Change.cshtml
@model ReqTrack.Application.Web.MVC.ViewModels.Requirements.ChangeRequirementViewModel

@{
    ViewData["Title"] = "Change requirement";
}

<div class="row" style="margin-top: 10px">
    <div class="col-xs-3">
        <h4>Actions</h4> <hr />
        <a asp-area="" asp-controller="Users" asp-action="Index" asp-route-id=@Model.ApplicationUserId class="btn btn-default actionButton">View profile</a>
        <a asp-area="" asp-controller="Projects" asp-action="CreateProject" class="btn btn-default actionButton">Create project</a>
        <a asp-area="" asp-controller="Projects" asp-action="Index" asp-route-id=@Model.ProjectId class="btn btn-default actionButton">View project</a>
    </div>

    <div class="col-xs-9">
        <h4>Change requirement of project: @Model.ProjectName</h4> <hr />
        <div>
            <form asp-action="Change">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <select asp-for="Type" asp-items="Model.Types" class="form-control"></select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Note" class="control-label"></label>
                    <input asp-for="Note" class="form-control" />
                    <span asp-validation-for="Note" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="ProjectId" class="form-control" />
                    <input asp-for="RequirementId" class="form-control" />
                    <input asp-for="ProjectName" class="form-control" />
                    <input asp-for="ApplicationUserId" class="form-control" />
                    <input asp-for="ApplicationUserName" class="form-control" />
                    @for (int i = 0; i < Model.Types.Length; ++i)
                    {
                        <input name="Types[@i].Value" type="hidden" value="@Model.Types[i].Value"/>
                        <input name="Types[@i].Text" type="hidden" value="@Model.Types[i].Text"/>
                    }
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ca/src/ReqTrack/Application.Web.MVC/Views/Requirements/Create.cshtml
@using Microsoft.Data.OData.Query.SemanticAst
@model ReqTrack.Application.Web.MVC.ViewModels.Requirements.AddRequirementViewModel

@{
    ViewData["Title"] = "Add requirement";
}

<div class="row" style="margin-top: 10px">
    <div class="col-xs-3">
        <h4>Actions</h4> <hr />
        <a asp-area="" asp-controller="Users" asp-action="Index" asp-route-id=@Model.ApplicationUserId class="btn btn-default actionButton">View profile</a>
        <a asp-area="" asp-controller="Projects" asp-action="CreateProject" class="btn btn-default actionButton">Create project</a>
        <a asp-area="" asp-controller="Projects" asp-action="Index" asp-route-id=@Model.ProjectId class="btn btn-default actionButton">View project</a>
    </div>

    <div class="col-xs-9">
        <h4>Add requirement to project: @Model.ProjectName</h4> <hr />
        <div>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <select asp-for="Type" asp-items="Model.Types" class="form-control"></select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Note" class="control-label"></label>
                    <input asp-for="Note" class="form-control" />
                    <span asp-validation-for="Note" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="ProjectId" class="form-control" />
                    <input asp-for="ApplicationUserId" class="form-control" />
                    <input asp-for="ProjectName" class="form-control" />
                    <input asp-for="ApplicationUserName" class="form-control"/>
                    @for (int i = 0; i < Model.Types.Length; ++i)
                    {
                        <input name="Types[@i].Value" type="hidden"/>
                        <input name="Types[@i].Text" type="hidden" />
                    }
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ca/src/ReqTrack/Application.Web.MVC/Views/Requirements/CreateRequirement.cshtml
@model ReqTrack.Application.Web.MVC.ViewModels.Requirements.RequirementViewModel

@{
    ViewData["Title"] = "CreateRequirement";
}

<h2>CreateRequirement</h2>

<h4>RequirementViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRequirement">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <input asp-for="ProjectId" class="form-control" />
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ca/src/ReqTrack/Application.Web.MVC/Views/Requirements/EditRequirement.cshtml
@model ReqTrack.Application.Web.MVC.ViewModels.Requirements.RequirementViewModel

@{
    ViewData["Title"] = "EditRequirement";
}

<h2>EditRequirement</h2>

<h4>RequirementViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditRequirement">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <input asp-for="ProjectId" class="form-control" />
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ca/src/ReqTrack/Application.Web.MVC/Views/Requirements/Index.cshtml
@model ReqTrack.Application.Web.MVC.ViewModels.Requirements.ViewRequirementViewModel

@{
    ViewData["Title"] = @Model.Title;
}

<div class="row" style="margin-top: 10px">
    <div class="col-xs-3">
        <h4>Actions</h4> <hr />
        <a asp-area="" asp-controller="Users" asp-action="Index" asp-route-id=@Model.ApplicationUserId class="btn btn-default actionButton">View profile</a>
        <a asp-area="" asp-controller="Projects" asp-action="CreateProject" class="btn btn-default actionButton">Create project</a>
        <a asp-area="" asp-controller="Projects" asp-action="Index" asp-route-id=@Model.ProjectId class="btn btn-default actionButton">View project</a>

        @if (Model.CanChange)
        {
            <h4>Requirement actions</h4> <hr/>
            var dict = new Dictionary<string, string> { { "projectId", Model.ProjectId }, { "id", Model.RequirementId } };
            <a asp-area="" asp-controller="Requirements" asp-action="Change" asp-all-route-data="dict" class="btn btn-default actionButton">Change</a>
            <a asp-area="" asp-controller="Requirements" asp-action="Delete" asp-all-route-data="dict" class="btn btn-default actionButton">Delete</a> 
        }
    </div>

    <div class="col-xs-9">
        <h4>Requirement: @Model.Title</h4> <hr />

        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.ProjectName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProjectName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.UserDisplayName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.UserDisplayName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Type)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Type)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Note)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Note)
                </dd>
            </dl>
        </div>
    </div>
</div>

ca/src/ReqTrack/Application.Web.MVC/Views/Requirements/ViewRequirement.cshtml
@model ReqTrack.Application.Web.MVC.ViewModels.Requirements.RequirementViewModel

@{
    ViewData["Title"] = "ViewRequirement";
}

<h2>ViewRequirement</h2>

<div>
    <h4>RequirementViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjectId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjectId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "EditRequirement", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>