ca/src/ReqTrack/Application.Web.MVC/ViewModels/UseCases/AddUseCaseViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using ReqTrack.Domain.Core.Entities.ValidationHelpers;

namespace ReqTrack.Application.Web.MVC.ViewModels.UseCases
{
    public class AddUseCaseViewModel : ViewModel
    {
        public AddUseCaseViewModel() : this(null, null) { }

        public AddUseCaseViewModel(string userId, string userName) : base(userId, userName)
        {
        }

        [HiddenInput]
        public string ProjectId { get; set; }
        
        [HiddenInput]
        [DisplayName("Project name")]
        public string ProjectName { get; set; }

        [DisplayName("Title")]
        [StringLength(UseCaseValidationHelper.MaximumTitleLength, ErrorMessage = "Title is too long.")]
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [DisplayName("Steps")]
        public string[] Steps { get; set; } = {};

        [DisplayName("Note")]
        [StringLength(UseCaseValidationHelper.MaximumNoteLength, ErrorMessage = "Note is too long.")]
        public string Note { get; set; }
    }
}

ca/src/ReqTrack/Application.Web.MVC/ViewModels/UseCases/ChangeUseCaseViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using ReqTrack.Domain.Core.Entities.ValidationHelpers;

namespace ReqTrack.Application.Web.MVC.ViewModels.UseCases
{
    public class ChangeUseCaseViewModel : ViewModel
    {
        public ChangeUseCaseViewModel() : this(null, null) { }

        public ChangeUseCaseViewModel(string userId, string userName) : base(userId, userName)
        {
        }

        [HiddenInput]
        public string ProjectId { get; set; }

        [HiddenInput]
        public string UseCaseId { get; set; }

        [HiddenInput]
        [DisplayName("Project name")]
        public string ProjectName { get; set; }

        [DisplayName("Title")]
        [StringLength(UseCaseValidationHelper.MaximumTitleLength, ErrorMessage = "Title is too long.")]
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [DisplayName("Steps")]
        public string[] Steps { get; set; } = {};

        [DisplayName("Note")]
        [StringLength(UseCaseValidationHelper.MaximumNoteLength, ErrorMessage = "Note is too long.")]
        public string Note { get; set; }
    }
}

ca/src/ReqTrack/Application.Web.MVC/ViewModels/UseCases/ViewUseCaseViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc;

namespace ReqTrack.Application.Web.MVC.ViewModels.UseCases
{
    public class ViewUseCaseViewModel : ViewModel
    {
        public ViewUseCaseViewModel(string userId, string userName) : base(userId, userName)
        {
        }

        [HiddenInput]
        public string ProjectId { get; set; }

        [HiddenInput]
        public string UseCaseId { get; set; }

        [HiddenInput]
        public string UserId { get; set; }

        [ReadOnly(true)]
        [DisplayName("Project name")]
        public string ProjectName { get; set; }

        [ReadOnly(true)]
        [DisplayName("Last changed by")]
        public string UserDisplayName { get; set; }

        [DisplayName("Title")]
        public string Title { get; set; }

        [DisplayName("Steps")]
        public string[] Steps { get; set; }

        [DisplayName("Note")]
        public string Note { get; set; }

        [HiddenInput]
        public bool CanChange { get; set; }
    }
}

ca/src/ReqTrack/Application.Web.MVC/Controllers/UseCasesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReqTrack.Application.Web.MVC.Factories;
using ReqTrack.Application.Web.MVC.Factories.Default;
using ReqTrack.Application.Web.MVC.ViewModels.UseCases;
using ReqTrack.Domain.Core.UseCases.Factories;
using ReqTrack.Domain.Core.UseCases.UseCases.AddUseCase;
using ReqTrack.Domain.Core.UseCases.UseCases.ChangeUseCase;
using ReqTrack.Domain.Core.UseCases.UseCases.DeleteUseCase;
using ReqTrack.Domain.Core.UseCases.UseCases.ViewUseCase;
using ReqTrack.Runtime.Core.Registry;

namespace ReqTrack.Application.Web.MVC.Controllers
{
    public class UseCasesController : Controller
    {
        private readonly IUseCaseUseCaseFactory _useCaseUseCaseFactory;

        private readonly IUseCasePresenterFactory _useCasePresenterFactory;

        public UseCasesController()
        {
            _useCaseUseCaseFactory = RegistryProxy.Get.GetFactory<IUseCaseUseCaseFactory>();
            _useCasePresenterFactory = new UseCasePresenterFactory();
        }

        [HttpGet]
        public IActionResult Index(string projectId, string id)
        {
            var uc = _useCaseUseCaseFactory.ViewUseCase;
            var request = new ViewUseCaseRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = projectId,
                UseCaseId = id,
            };

            var presenter = _useCasePresenterFactory.ViewUseCase(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpGet]
        public IActionResult Create(string id)
        {
            var uc = _useCaseUseCaseFactory.AddUseCase;
            var request = new AddUseCaseInitialRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = id,
            };

            var presenter = _useCasePresenterFactory.AddUseCase(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpPost]
        public IActionResult Create(AddUseCaseViewModel vm)
        {
            var uc = _useCaseUseCaseFactory.AddUseCase;
            var request = new AddUseCaseRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = vm.ProjectId,
                Title = vm.Title,
                Note = vm.Note,
                Steps = vm.Steps,
            };

            var presenter = _useCasePresenterFactory.AddUseCase(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            return RedirectToAction(nameof(Index), new
            {
                projectId = presenter.Response.ProjectId,
                id = presenter.Response.GivenId
            });
        }

        [HttpGet]
        public IActionResult Change(string projectId, string id)
        {
            var uc = _useCaseUseCaseFactory.ChangeUseCase;
            var request = new ChangeUseCaseInitialRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = projectId,
                UseCaseId = id,
            };

            var presenter = _useCasePresenterFactory.ChangeUseCase(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpPost]
        public IActionResult Change(ChangeUseCaseViewModel vm)
        {
            var uc = _useCaseUseCaseFactory.ChangeUseCase;
            var request = new ChangeUseCaseRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = vm.ProjectId,
                UseCaseId = vm.UseCaseId,
                Title = vm.Title,
                Note = vm.Note,
                Steps = vm.Steps,
            };

            var presenter = _useCasePresenterFactory.ChangeUseCase(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            return RedirectToAction(nameof(Index), new
            {
                projectId = presenter.Response.ProjectId,
                id = presenter.Response.UseCaseId,
            });
        }

        [HttpGet]
        public IActionResult Delete(string projectId, string id)
        {
            var uc = _useCaseUseCaseFactory.DeleteUseCase;
            var request = new DeleteUseCaseRequest(HttpContext.Session.GetString("UserId"))
            {
                ProjectId = projectId,
                UseCaseId = id,
            };

            var presenter = _useCasePresenterFactory.Default<DeleteUseCaseResponse>(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return RedirectToAction(nameof(Index), "Projects",
                new
                {
                    id = projectId,
                    showRequirements = false,
                    showTrue = false
                }
            );
        }
    }
}

ca/src/ReqTrack/Application.Web.MVC/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReqTrack.Application.Web.MVC.Factories;
using ReqTrack.Application.Web.MVC.Factories.Default;
using ReqTrack.Application.Web.MVC.ViewModels.Users;
using ReqTrack.Domain.Core.UseCases.Factories;
using ReqTrack.Domain.Core.UseCases.Users.AuthorizeUser;
using ReqTrack.Domain.Core.UseCases.Users.ChangeInformation;
using ReqTrack.Domain.Core.UseCases.Users.ChangePassword;
using ReqTrack.Domain.Core.UseCases.Users.DeleteUser;
using ReqTrack.Domain.Core.UseCases.Users.RegisterUser;
using ReqTrack.Domain.Core.UseCases.Users.ViewProfile;
using ReqTrack.Runtime.Core.Registry;

namespace ReqTrack.Application.Web.MVC.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly IUserUseCaseFactory _userUseCaseFactory;

        private readonly IUserPresenterFactory _userPresenterFactory;

        public UsersController()
        {
            _userUseCaseFactory = RegistryProxy.Get.GetFactory<IUserUseCaseFactory>();
            _userPresenterFactory = new UserPresenterFactory();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult LogIn()
        {
            return View(new LogInViewModel());
        }

        [HttpPost]
        [AllowAnonymous]
        [AutoValidateAntiforgeryToken]
        public IActionResult LogIn(LogInViewModel vm)
        {
            var uc = _userUseCaseFactory.AuthorizeUser;
            var request = new AuthorizeUserRequest(null)
            {
                UserName = vm.UserName,
                Password = vm.Password,
            };

            var presenter = _userPresenterFactory.Default<AuthorizeUserResponse>(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            HttpContext.Session.SetString("UserId", presenter.Response.UserId);
            HttpContext.Session.SetString("UserName", presenter.Response.DisplayName);

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, vm.UserName),
            };

            var userIdentity = new ClaimsIdentity(claims, "login");

            var principal = new ClaimsPrincipal(userIdentity);
            HttpContext.SignInAsync(principal).Wait();

            return RedirectToAction(nameof(Index), new {id = presenter.Response.UserId});
        }

        [HttpGet]
        public IActionResult SignOut()
        {
            HttpContext.Session.Clear();

            HttpContext.SignOutAsync().Wait();
            return Redirect("/");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult RegisterUser()
        {
            return View(new RegisterUserViewModel());
        }

        [HttpPost]
        [AllowAnonymous]
        [AutoValidateAntiforgeryToken]
        public IActionResult RegisterUser(RegisterUserViewModel vm)
        {
            var uc = _userUseCaseFactory.RegisterUser;
            var request = new RegisterUserRequest
            {
                UserName = vm.UserName,
                DisplayName = vm.DisplayName,
                Password = vm.Password,
                ConfirmedPassword = vm.ConfirmPassword,
            };

            var presenter = _userPresenterFactory.Default<RegisterUserResponse>(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            return Redirect(nameof(LogIn));
        }

        [HttpGet]
        public IActionResult Index(string id)
        {
            var uc = _userUseCaseFactory.ViewProfile;
            var request = new ViewProfileRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = id,
            };

            var presenter = _userPresenterFactory.ViewProfile(HttpContext.Session, TempData, ModelState);
            if(!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpGet]
        public IActionResult ChangeInformation(string id)
        {
            var uc = _userUseCaseFactory.ChangeInformation;
            var request = new ChangeInformationInitialRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = id,
            };

            var presenter = _userPresenterFactory.ChangeInformation(HttpContext.Session, TempData, ModelState);
            if(!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangeInformation(ChangeInformationViewModel vm)
        {
            var uc = _userUseCaseFactory.ChangeInformation;
            var request = new ChangeInformationRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = vm.ApplicationUserId,
                DisplayName = vm.DisplayName,
            };

            var presenter = _userPresenterFactory.ChangeInformation(HttpContext.Session, TempData, ModelState);
            if(!uc.Execute(presenter, request)) { return View(vm); }

            return RedirectToAction(nameof(Index), new { id = presenter.Response.UserId });
        }

        [HttpGet]
        public IActionResult ChangePassword(string id)
        {
            var uc = _userUseCaseFactory.ChangePassword;
            var request = new ChangePasswordInitialRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = id,
            };

            var presenter = _userPresenterFactory.ChangePassword(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return View(presenter.ViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangePassword(ChangePasswordViewModel vm)
        {
            var uc = _userUseCaseFactory.ChangePassword;
            var request = new ChangePasswordRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = vm.ApplicationUserId,
                OldPassword = vm.OldPassword,
                NewPassword = vm.NewPassword,
                ConfirmedPassword = vm.ConfirmedPassword,
            };

            var presenter = _userPresenterFactory.ChangePassword(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return View(vm); }

            return RedirectToAction(nameof(Index), new { id = presenter.Response.UserId });
        }

        [HttpGet]
        public IActionResult DeleteUser(string id)
        {
            var uc = _userUseCaseFactory.DeleteUser;
            var request = new DeleteUserRequest(HttpContext.Session.GetString("UserId"))
            {
                UserId = id,
            };

            var presenter = _userPresenterFactory.Default<DeleteUserResponse>(HttpContext.Session, TempData, ModelState);
            if (!uc.Execute(presenter, request)) { return NotFound(); }

            return RedirectToAction(nameof(LogIn));
        }
    }
}

ca/src/ReqTrack/Application.Web.MVC/Views/UseCases/Change.cshtml
@model ReqTrack.Application.Web.MVC.ViewModels.UseCases.ChangeUseCaseViewModel

@{
    ViewData["Title"] = "Change use case";
}

<div class="row" style="margin-top: 10px">
    <div class="col-xs-3">
        <h4>Actions</h4> <hr />
        <a asp-area="" asp-controller="Users" asp-action="Index" asp-route-id=@Model.ApplicationUserId class="btn btn-default actionButton">View profile</a>
        <a asp-area="" asp-controller="Projects" asp-action="CreateProject" class="btn btn-default actionButton">Create project</a>
        <a asp-area="" asp-controller="Projects" asp-action="Index" asp-route-id=@Model.ProjectId class="btn btn-default actionButton">View project</a>
    </div>

    <div class="col-xs-9">
        <h4>Change use case of project: @Model.ProjectName</h4> <hr />
        <div>
            <form asp-action="Change">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Note" class="control-label"></label>
                    <input asp-for="Note" class="form-control" />
                    <span asp-validation-for="Note" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="ProjectId" class="form-control" />
                    <input asp-for="UseCaseId" class="form-control" />
                    <input asp-for="ProjectName" class="form-control" />
                    <input asp-for="ApplicationUserId" class="form-control" />
                    <input asp-for="ApplicationUserName" class="form-control" />
                </div>
                <div class="form-group">
                    <table class="table" id="stepTable">
                        <tr id="stepTableHeader">
                            <th class="actionButton">Step</th>
                            <th colspan="3"><button class="btn btn-default tableButton" name="add">Add</button></th>
                        </tr>
                        @foreach (var step in Model.Steps)
                        {
                        <tr>
                            <td><input name="Steps[]" class="form-control" value="@step" /></td>
                            <td><button class="btn btn-default tableButton" name="up">Up</button></td>
                            <td><button class="btn btn-default tableButton" name="down">Down</button></td>
                            <td><button class="btn btn-default tableButton" name="del" onclick="remove_row(this)">Delete</button></td>
                        </tr>
                        }
                    </table>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ca/src/ReqTrack/Application.Web.MVC/Views/UseCases/Create.cshtml
@model ReqTrack.Application.Web.MVC.ViewModels.UseCases.AddUseCaseViewModel

@{
    ViewData["Title"] = "Add use case";
}

<div class="row" style="margin-top: 10px">
    <div class="col-xs-3">
        <h4>Actions</h4> <hr />
        <a asp-area="" asp-controller="Users" asp-action="Index" asp-route-id=@Model.ApplicationUserId class="btn btn-default actionButton">View profile</a>
        <a asp-area="" asp-controller="Projects" asp-action="CreateProject" class="btn btn-default actionButton">Create project</a>
        <a asp-area="" asp-controller="Projects" asp-action="Index" asp-route-id=@Model.ProjectId class="btn btn-default actionButton">View project</a>
    </div>

    <div class="col-xs-9">
        <h4>Add use case to project: @Model.ProjectName</h4> <hr />
        <div>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Note" class="control-label"></label>
                    <input asp-for="Note" class="form-control" />
                    <span asp-validation-for="Note" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="ProjectId" class="form-control" />
                    <input asp-for="ProjectName" class="form-control" />
                    <input asp-for="ApplicationUserId" class="form-control" />
                    <input asp-for="ApplicationUserName" class="form-control" />
                </div>
                <div class="form-group">
                    <table class="table" id="stepTable">
                        <tr id="stepTableHeader">
                            <th class="actionButton">Step</th>
                            <th colspan="3"><button class="btn btn-default tableButton" name="add">Add</button></th>
                        </tr>
                        @foreach (var step in Model.Steps)
                        {
                            <tr>
                                <td><input name="Steps[]" class="form-control" value="@step" /></td>
                                <td><button class="btn btn-default tableButton" name="up">Up</button></td>
                                <td><button class="btn btn-default tableButton" name="down">Down</button></td>
                                <td><button class="btn btn-default tableButton" name="del" onclick="remove_row(this)">Delete</button></td>
                            </tr>
                        }
                    </table>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ca/src/ReqTrack/Application.Web.MVC/Views/UseCases/Index.cshtml
@model ReqTrack.Application.Web.MVC.ViewModels.UseCases.ViewUseCaseViewModel

@{
    ViewData["Title"] = @Model.Title;
}

<div class="row" style="margin-top: 10px">
    <div class="col-xs-3">
        <h4>Actions</h4> <hr />
        <a asp-area="" asp-controller="Users" asp-action="Index" asp-route-id=@Model.ApplicationUserId class="btn btn-default actionButton">View profile</a>
        <a asp-area="" asp-controller="Projects" asp-action="CreateProject" class="btn btn-default actionButton">Create project</a>
        <a asp-area="" asp-controller="Projects" asp-action="Index" asp-route-id=@Model.ProjectId class="btn btn-default actionButton">View project</a>

        @if (Model.CanChange)
        {
            <h4>Use case actions</h4> <hr />
            var dict = new Dictionary<string, string> { { "projectId", Model.ProjectId }, { "id", Model.UseCaseId } };
            <a asp-area="" asp-controller="UseCases" asp-action="Change" asp-all-route-data="dict" class="btn btn-default actionButton">Change</a>
            <a asp-area="" asp-controller="UseCases" asp-action="Delete" asp-all-route-data="dict" class="btn btn-default actionButton">Delete</a>
        }
    </div>

    <div class="col-xs-9">
        <h4>Use cases: @Model.Title</h4> <hr />
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.ProjectName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProjectName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.UserDisplayName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.UserDisplayName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Note)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Note)
                </dd>
            </dl>
            <h4>Steps</h4> <hr />
            <table class="table">
                @if (Model.Steps.Any())
                {
                    <tr><th>Step</th></tr>
                    foreach (var s in Model.Steps)
                    {
                        <tr><td>@s</td></tr>
                    }
                }
                else
                {
                    <tr>No steps for this use case</tr>
                }
            </table>
        </div>
    </div>
</div>